check:
  - overlays-build
overlays_dir: overlays
overlays:
  - name: ps-cv-ocr
    build:
      build-stratergy: Dockerfile
      registry: quay.io
      registry-org: thoth-station
      registry-project: ps-cv-ocr
      registry-secret: thoth-station-thoth-pusher-secret

  - name: ps-cv-pytorch
    build:
      build-stratergy: Dockerfile
      registry: quay.io
      registry-org: thoth-station
      registry-project: ps-cv-pytorch
      registry-secret: thoth-station-thoth-pusher-secret

  - name: ps-cv-tensorflow
    build:
      build-stratergy: Dockerfile
      registry: quay.io
      registry-org: thoth-station
      registry-project: ps-cv-tensorflow
      registry-secret: thoth-station-thoth-pusher-secret
